name: gpp_app
description: Goodpoopee app of Team urillbwa, SWMaestro 11th.
author: Gyeongmin Ha <gaonrudal@gmail.com>

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State management
  provider: ^4.3.2+2
  # handling rest api
  dio: ^3.0.10
  # platform-specific persistent storage for simple data
  shared_preferences: '>=0.5.12 <2.0.0'
  # serialization JSON
  json_annotation: ^3.0.0

  intl: ^0.16.1 # provides internationalization and localization facilities, including message translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  flutter_svg: ^0.18.0 # help us to use SVG in our app
  fab_circular_menu: ^1.0.0 # create a nice circular menu using a Floating Action Button.
  fl_chart: ^0.11.1 # A library to draw fantastic charts in Flutter
  flutter_slidable: ^0.5.7 # A Flutter implementation of slidable list item with directional slide actions that can be dismissed.

  # for streaming
  flutter_vlc_player: ^4.0.2
  # for local file saving
  image_gallery_saver: ^1.6.1
  # loading image
  transparent_image: ^1.0.0
  # launcher icon
  flutter_launcher_icons: ^0.8.1
  # lottie
  lottie: ^0.7.0+1
  add_thumbnail: ^0.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # serialization JSON
  build_runner: ^1.0.0
  json_serializable: ^3.2.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/icons/
  - assets/lang/
  - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansKR-light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/gpp_icon.png"